version: '3.4'

services:
  tokenserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  vendor.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

